### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by kresnasatya** [kresnasatya/adminkit#1]
- [ ] Dynamic menu from database
- [ ] Add auth
- [ ] Implement Role and Permission with spatie package (spatie permission)

**Comment by rizkhal** [comment]
how to contribute?

**Comment by kresnasatya** [comment]
Sorry, I close this issue because I think that actually I or maybe other developers need the UI of AdminKit instead of things that I mention earlier like dynamic menu from database, auth, and role permissions. I will let developers to take care those things.

So, I will focus on porting UI of AdminKit to blade file. Here's the project that I working on: https://github.com/kresnasatya/adminkit-blade. Feel free to take a look. Thank you.
